"""Added indexes for period times.

Revision ID: 90ae5785df01
Revises: d0f896c02017
Create Date: 2020-06-14 20:03:28.965285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ae5785df01'
down_revision = 'd0f896c02017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_period_ended_at'), 'period', ['ended_at'], unique=False)
    op.create_index(op.f('ix_period_started_at'), 'period', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_started_at'), table_name='period')
    op.drop_index(op.f('ix_period_ended_at'), table_name='period')
    # ### end Alembic commands ###
